### ISSUE TITLE
Cannot open Add dialogue

### ISSUE THREAD

**Issue by dotancohen** [Arthur-Milchior/anki-Multi-column-edit-window#2] opened 2019-04-22 15:00 UTC
On Anki Version 2.1.11 (3cf770c7) with Qt 5.12.1 PyQt 5.11.3 and only a single addon enabled (this one) I get the following error when I press the Add button to add new cards:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.11 (3cf770c7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Linux
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 85, in _onCmd
  File "aqt/webview.py", line 360, in _onBridgeCmd
  File "aqt/toolbar.py", line 56, in _linkHandler
  File "aqt/toolbar.py", line 71, in _addLinkHandler
  File "aqt/main.py", line 830, in onAddCard
  File "aqt/__init__.py", line 82, in open
  File "aqt/addcards.py", line 27, in __init__
  File "aqt/addcards.py", line 39, in setupEditor
  File "<decorator-gen-2>", line 2, in __init__
  File "anki/hooks.py", line 74, in decorator_wrapper
  File "anki/hooks.py", line 65, in repl
  File "aqt/editor.py", line 53, in __init__
  File "aqt/editor.py", line 113, in setupWeb
<class 'TypeError'>: not enough arguments for format string
```

The dialogue never opens, I get this message instead.

**Comment by dotancohen** [comment] 2019-04-22 15:01
This is the checked-out commit for the addon, which seems to be the latest commit:

```
commit 70f92cd5f62bd4feda5422701bd01acb41ed48ce (HEAD -> master, origin/master, origin/HEAD)
Author: Arthur-Milchior <arthur@milchior.fr>
Date:   Fri Apr 12 11:28:31 2019 +0200

    merging with frozen field
```

**Comment by Arthur-Milchior** [comment] 2019-06-28 13:19
I must plainly admit that this error message makes no sens to me. I even did take a look at anki 2.1.11 and it still puzzles me.
Can you first update the add-on, and may be update anki to latest version, and try again ? Because I don't know what else to advice right now

**Comment by Arthur-Milchior** [comment] 2020-01-09 23:06
I had no news for monthes, so I assume the problem is no longer relevant. I close it

**Closed by Arthur-Milchior** 2020-01-09 23:06 UTC
